apiVersion: v1
kind: Service
metadata:
    name: "kubedeploytestapp-91b2"
    labels:
        app: "kubedeploytestapp-91b2"
spec:
    type: LoadBalancer
    ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: http
    selector:
        app: "kubedeploytestapp-91b2"