on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: jspcontainerregistry.azurecr.io
        username: ${{ secrets.acr_jspcontainerregistry_username }}
        password: ${{ secrets.acr_jspcontainerregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE" -f  "DataIntakeApp/Dockerfile" -t jspcontainerregistry.azurecr.io/kubedeploytestapp:${{ github.sha }} --label dockerfile-path=DataIntakeApp/Dockerfile
        docker push jspcontainerregistry.azurecr.io/kubedeploytestapp:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubedeploytestapp_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubedeploytestappa69b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubedeploytestappa69b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubedeploytestappa69b
        container-registry-url: jspcontainerregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_jspcontainerregistry_username }}
        container-registry-password: ${{ secrets.acr_jspcontainerregistry_password }}
        secret-name: kubedeploytedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kubedeploytestappa69b
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          jspcontainerregistry.azurecr.io/kubedeploytestapp:${{ github.sha }}
        imagepullsecrets: |
          kubedeploytedockerauth
